version: '2'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=$SECRET_KEY
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server
  
  nginx:
    #container_name: nginx
    restart: always
    #build: ./nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_app
    volumes:
      - /etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - /var/www/certbot/:/var/www/certbot/:ro
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /var/www/certbot/:/var/www/certbot/:rw
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
  
  bot:
    container_name: bot
    restart: always
    build: ./bot
    depends_on:
      - flask_app
    environment:
      - SECRET_KEY=$SECRET_KEY
    command: python3 -u bot.py