version: '2'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=$SECRET_KEY
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:create_app()
  
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_app
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/profitgreen.tk/fullchain.pem:/etc/letsencrypt/live/profitgreen.tk/fullchain.pem
      - /etc/letsencrypt/live/profitgreen.tk/privkey.pem:/etc/letsencrypt/live/profitgreen.tk/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
  
  bot:
    container_name: bot
    restart: always
    build: ./bot
    depends_on:
      - flask_app
    environment:
      - SECRET_KEY=$SECRET_KEY
    command: python3 -u bot.py